id: A4D9267C7
base_file: fCF0E.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:11:05.237692
  last_modified_at: 2022-05-31 05:11:05.237696
