id: A4D9267C7
base_file: f9C52.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:11:05.235226
  last_modified_at: 2022-05-31 05:11:05.235253
